src/Entity/VeterinaryClinic.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VeterinaryClinicRepository")
 */
class VeterinaryClinic
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $street_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $indice_street_number;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $complementary;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Dispense", mappedBy="veterinary_clinic", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    private $dispenses;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStreetNumber(): ?int
    {
        return $this->street_number;
    }

    public function setStreetNumber(?int $street_number): self
    {
        $this->street_number = $street_number;

        return $this;
    }

    public function getIndiceStreetNumber(): ?string
    {
        return $this->indice_street_number;
    }

    public function setIndiceStreetNumber(?string $indice_street_number): self
    {
        $this->indice_street_number = $indice_street_number;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getComplementary(): ?string
    {
        return $this->complementary;
    }

    public function setComplementary(?string $complementary): self
    {
        $this->complementary = $complementary;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getDispenses()
    {
        return $this->dispenses;
    }

    /**
     * @param mixed $dispenses
     * @return VeterinaryClinic
     */
    public function setDispenses($dispenses)
    {
        $this->dispenses = $dispenses;
        return $this;
    }


}

src/Form/VeterinaryClinicType.php
<?php

namespace App\Form;

use App\Entity\VeterinaryClinic;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VeterinaryClinicType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('street_number')
            ->add('indice_street_number')
            ->add('street')
            ->add('complementary')
            ->add('zip_code')
            ->add('city')
            ->add('phone')
            ->add('email')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => VeterinaryClinic::class,
        ]);
    }
}

src/Controller/VeterinaryClinicController.php
<?php

namespace App\Controller;

use App\Entity\VeterinaryClinic;
use App\Entity\VeterinaryClinicSearch;
use App\Form\VeterinaryClinicSearchType;
use App\Form\VeterinaryClinicType;
use App\Repository\VeterinaryClinicRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/veterinary/clinic")
 */
class VeterinaryClinicController extends AbstractController
{
    /**
     * @var VeterinaryClinicRepository
     */
    private $repository;

    public function __construct(VeterinaryClinicRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }

    /**
     * @Route("/", name="veterinary_clinic_index", methods={"GET"})
     */
    public function index(VeterinaryClinicRepository $veterinaryClinicRepository): Response
    {
        return $this->render('veterinary_clinic/index.html.twig', [
            'veterinary_clinics' => $veterinaryClinicRepository->findAll(),
        ]);
    }

    /**
     * @Route("/search", name="veterinary_clinic_search")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function clinicSearch(PaginatorInterface $paginator, Request $request): Response
    {
        $search = new VeterinaryClinicSearch();
        $form = $this->createForm(VeterinaryClinicSearchType::class, $search);
        $form->handleRequest($request);

        $clinics = $paginator->paginate(
            $this->repository->findClinicsByLocation($search),
            $request->query->getInt('page', 1),
            12
        );
        return $this->render('veterinary_clinic/search.html.twig', [
            'current_menu' => 'clinics',
            'clinics' => $clinics,
            'form' => $form->createView()
        ]);

    }

    /**
     * @Route("/new", name="veterinary_clinic_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $veterinaryClinic = new VeterinaryClinic();
        $form = $this->createForm(VeterinaryClinicType::class, $veterinaryClinic);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($veterinaryClinic);
            $entityManager->flush();

            return $this->redirectToRoute('veterinary_clinic_index');
        }

        return $this->render('veterinary_clinic/new.html.twig', [
            'veterinary_clinic' => $veterinaryClinic,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="veterinary_clinic_show", methods={"GET"})
     */
    public function show(VeterinaryClinic $veterinaryClinic): Response
    {
        return $this->render('veterinary_clinic/show.html.twig', [
            'veterinary_clinic' => $veterinaryClinic,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="veterinary_clinic_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, VeterinaryClinic $veterinaryClinic): Response
    {
        $form = $this->createForm(VeterinaryClinicType::class, $veterinaryClinic);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('veterinary_clinic_index');
        }

        return $this->render('veterinary_clinic/edit.html.twig', [
            'veterinary_clinic' => $veterinaryClinic,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="veterinary_clinic_delete", methods={"DELETE"})
     */
    public function delete(Request $request, VeterinaryClinic $veterinaryClinic): Response
    {
        if ($this->isCsrfTokenValid('delete' . $veterinaryClinic->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($veterinaryClinic);
            $entityManager->flush();
        }

        return $this->redirectToRoute('veterinary_clinic_index');
    }
}

templates/veterinary_clinic/_delete_form.html.twig
<form method="post" action="{{ path('veterinary_clinic_delete', {'id': veterinary_clinic.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ veterinary_clinic.id) }}">
    <button class="btn">Delete</button>
</form>

templates/veterinary_clinic/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/veterinary_clinic/_veterinary_clinic.html.twig
<div class="card mb-4">
    <div class="card-body">
        <h5 class="card-title">

                {{ clinic.name }}

        </h5>
        <p class="card-text">{{ clinic.streetnumber }} {{ clinic.indicestreetnumber }} {{ clinic.street }}</p>
        <p class="card-text"> {{ clinic.complementary }}</p>
        <p class="card-text">{{ clinic.zipcode }} {{ clinic.city }} </p>
        <p class="card-text">Tél : {{ clinic.phone }} </p>
        <p class="card-text"> Email : {{ clinic.email }}</p>
        {% for dispense in dispenses %}
        <p class="card-text">{{ clinic.dispense }}</p>
        {% endfor %}

    </div>
</div>

templates/veterinary_clinic/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit VeterinaryClinic{% endblock %}

{% block body %}
    <h1>Edit VeterinaryClinic</h1>

    {{ include('veterinary_clinic/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('veterinary_clinic_index') }}">back to list</a>

    {{ include('veterinary_clinic/_delete_form.html.twig') }}
{% endblock %}

templates/veterinary_clinic/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}VeterinaryClinic index{% endblock %}

{% block body %}
    <h1>VeterinaryClinic index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Street_number</th>
                <th>Indice_street_number</th>
                <th>Street</th>
                <th>Complementary</th>
                <th>Zip_code</th>
                <th>City</th>
                <th>Phone</th>
                <th>Email</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for veterinary_clinic in veterinary_clinics %}
            <tr>
                <td>{{ veterinary_clinic.id }}</td>
                <td>{{ veterinary_clinic.name }}</td>
                <td>{{ veterinary_clinic.streetNumber }}</td>
                <td>{{ veterinary_clinic.indiceStreetNumber }}</td>
                <td>{{ veterinary_clinic.street }}</td>
                <td>{{ veterinary_clinic.complementary }}</td>
                <td>{{ veterinary_clinic.zipCode }}</td>
                <td>{{ veterinary_clinic.city }}</td>
                <td>{{ veterinary_clinic.phone }}</td>
                <td>{{ veterinary_clinic.email }}</td>
                <td>
                    <a href="{{ path('veterinary_clinic_show', {'id': veterinary_clinic.id}) }}">show</a>
                    <a href="{{ path('veterinary_clinic_edit', {'id': veterinary_clinic.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('veterinary_clinic_new') }}">Create new</a>
{% endblock %}

templates/veterinary_clinic/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New VeterinaryClinic{% endblock %}

{% block body %}{{ ext }}
    <h1>Create new VeterinaryClinic</h1>

    {{ include('veterinary_clinic/_form.html.twig') }}

    <a href="{{ path('veterinary_clinic_index') }}">back to list</a>
{% endblock %}

templates/veterinary_clinic/search.html.twig
{% block body %}

<div class="container">
    {{ form_start(form) }}
    <div class="form-row align-items-end">
        <div class="col">
            {{ form_row(form.zipCode) }}
        </div>
        <div class="col">
            {{ form_row(form.city) }}
        </div>
        <div class="col">
            <div class="form-group">
                <button class="btn btn-primary">Rechercher</button>
            </div>
        </div>
    </div>
    {{ form_end(form) }}
</div>

<div class="container mt-4">
    <h1>Voir toutes nos cliniques</h1>

    <div class="row">
        {% for clinic in clinics %}
            <div class="col-md-4">
                {% include 'veterinary_clinic/_veterinary_clinic.html.twig' %}
            </div>
        {% endfor %}
    </div>

    <div class="pagination">
        {{ knp_pagination_render(clinics) }}
    </div>
</div>

{% endblock %}

templates/veterinary_clinic/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}VeterinaryClinic{% endblock %}

{% block body %}
    <h1>VeterinaryClinic</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ veterinary_clinic.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ veterinary_clinic.name }}</td>
            </tr>
            <tr>
                <th>Street_number</th>
                <td>{{ veterinary_clinic.streetNumber }}</td>
            </tr>
            <tr>
                <th>Indice_street_number</th>
                <td>{{ veterinary_clinic.indiceStreetNumber }}</td>
            </tr>
            <tr>
                <th>Street</th>
                <td>{{ veterinary_clinic.street }}</td>
            </tr>
            <tr>
                <th>Complementary</th>
                <td>{{ veterinary_clinic.complementary }}</td>
            </tr>
            <tr>
                <th>Zip_code</th>
                <td>{{ veterinary_clinic.zipCode }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ veterinary_clinic.city }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ veterinary_clinic.phone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ veterinary_clinic.email }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('veterinary_clinic_index') }}">back to list</a>

    <a href="{{ path('veterinary_clinic_edit', {'id': veterinary_clinic.id}) }}">edit</a>

    {{ include('veterinary_clinic/_delete_form.html.twig') }}
{% endblock %}