src/Entity/Opinion.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OpinionRepository")
 */
class Opinion
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $theme;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_post;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(string $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    public function getDatePost(): ?\DateTimeInterface
    {
        return $this->date_post;
    }

    public function setDatePost(\DateTimeInterface $date_post): self
    {
        $this->date_post = $date_post;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }
}

src/Form/OpinionType.php
<?php

namespace App\Form;

use App\Entity\Opinion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OpinionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('theme')
            ->add('date_post')
            ->add('text')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Opinion::class,
        ]);
    }
}

src/Controller/OpinionController.php
<?php

namespace App\Controller;

use App\Entity\Opinion;
use App\Form\OpinionType;
use App\Repository\OpinionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/opinion")
 */
class OpinionController extends AbstractController
{
    /**
     * @Route("/", name="opinion_index", methods={"GET"})
     */
    public function index(OpinionRepository $opinionRepository): Response
    {
        return $this->render('opinion/index.html.twig', [
            'opinions' => $opinionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="opinion_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $opinion = new Opinion();
        $form = $this->createForm(OpinionType::class, $opinion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($opinion);
            $entityManager->flush();

            return $this->redirectToRoute('opinion_index');
        }

        return $this->render('opinion/new.html.twig', [
            'opinion' => $opinion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="opinion_show", methods={"GET"})
     */
    public function show(Opinion $opinion): Response
    {
        return $this->render('opinion/show.html.twig', [
            'opinion' => $opinion,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="opinion_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Opinion $opinion): Response
    {
        $form = $this->createForm(OpinionType::class, $opinion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('opinion_index');
        }

        return $this->render('opinion/edit.html.twig', [
            'opinion' => $opinion,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="opinion_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Opinion $opinion): Response
    {
        if ($this->isCsrfTokenValid('delete'.$opinion->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($opinion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('opinion_index');
    }
}

templates/opinion/_delete_form.html.twig
<form method="post" action="{{ path('opinion_delete', {'id': opinion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ opinion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/opinion/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/opinion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Opinion{% endblock %}

{% block body %}
    <h1>Edit Opinion</h1>

    {{ include('opinion/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('opinion_index') }}">back to list</a>

    {{ include('opinion/_delete_form.html.twig') }}
{% endblock %}

templates/opinion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Opinion index{% endblock %}

{% block body %}
    <h1>Opinion index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Theme</th>
                <th>Date_post</th>
                <th>Text</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for opinion in opinions %}
            <tr>
                <td>{{ opinion.id }}</td>
                <td>{{ opinion.theme }}</td>
                <td>{{ opinion.datePost ? opinion.datePost|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ opinion.text }}</td>
                <td>
                    <a href="{{ path('opinion_show', {'id': opinion.id}) }}">show</a>
                    <a href="{{ path('opinion_edit', {'id': opinion.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('opinion_new') }}">Create new</a>
{% endblock %}

templates/opinion/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Opinion{% endblock %}

{% block body %}
    <h1>Create new Opinion</h1>

    {{ include('opinion/_form.html.twig') }}

    <a href="{{ path('opinion_index') }}">back to list</a>
{% endblock %}

templates/opinion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Opinion{% endblock %}

{% block body %}
    <h1>Opinion</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ opinion.id }}</td>
            </tr>
            <tr>
                <th>Theme</th>
                <td>{{ opinion.theme }}</td>
            </tr>
            <tr>
                <th>Date_post</th>
                <td>{{ opinion.datePost ? opinion.datePost|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Text</th>
                <td>{{ opinion.text }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('opinion_index') }}">back to list</a>

    <a href="{{ path('opinion_edit', {'id': opinion.id}) }}">edit</a>

    {{ include('opinion/_delete_form.html.twig') }}
{% endblock %}